### ISSUE TITLE
How should we handle errors?

### ISSUE THREAD

**Issue by benjaminww** [aikoven/typescript-fsa-redux-saga#11]
Hi,

Thanks a lot for creating your typescript libraries. I'm really enjoying using them. I'm hoping to gain some clarity on how to best handle errors in my sagas.

For example, I have the following saga:
```
export const postTopic = bindAsyncAction(actionCreators.postTopic, { skipStartedAction: true })(
  function*(payload): SagaIterator {
    const newTopic = yield call(axios.post, "/api/topics", payload);

    return newTopic.data;
  }
);

export default [
  takeLatest<Action<PostTopicPayload>>(
    actionCreators.postTopic.started,
    (action) => postTopic(action.payload)
  )
];
```

I define my rootSaga as follows:
```
export default function* rootSaga() {
  yield all([ ...topicsSagas ]);
}
```

I purposely sent a bad request to test error handling and your higher-order saga correctly fires the .failed() event. However, after dispatching the .failed() it seems my sagas are no longer listening to actions. It's as if all my sagas are stopped. I get this error in my browser console:
```
The above error occurred in task anonymous: created by takeLatest(TOPICS/POST_TOPIC_STARTED, )
    created by rootSaga
Tasks cancelled due to error:
takeLatest(TOPICS/POST_TOPIC_STARTED, )...
```

I'm not sure why this happens. Am I misunderstanding how to use the library? Would you please provide an example of how to handle errors? Thanks a lot.

**Comment by aikoven** [comment]
Errors are rethrown from bound generators, so you get an uncaught error. If you only want to hangle errors in reducers, you can use something like this:

```ts
export default [
  takeLatest<Action<PostTopicPayload>>(
    actionCreators.postTopic.started,
    function*(action) {
      try {
        yield call(postTopic, action.payload);
      } catch (e) { /* ignore */ }
    }
  )
];
```
