### ISSUE TITLE
Hard dependency on redux-saga (not working with redux-saga v1.0.0-beta.0)

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [aikoven/typescript-fsa-redux-saga#6]
Ive upgraded to redux-saga v1.0.0-beta.0. Suddenly all sagas created with bindAsyncAction wouldn't work anymore. According to a conversation with Mateusz Burzyński on github:

>  I've switched to using symbols in effect descriptors
> so the yielded effects by this library
> might not get interpreted OK
> I think this library should move from having redux-saga as dep to peerDep
> and allow v1-beta
> would u like to create a PR for it?

I'll have a look at making a PR for that.

**Comment by aikoven** [comment]
Fixed in [`v1.1.0`](https://github.com/aikoven/typescript-fsa-redux-saga/releases/tag/v1.1.0).
